### PR TITLE
Add back to top button

### LINKED ISSUE #130: back to top button
I think adding back to top button to the readme file will make it more interacting and easy for people to go back the the start of the page

### PR DESCRIPTION
**Pull request by git-create-devben**
# Pull Request

## Description
I add back to top button to be easy for folks to go back up after they're done checking the readme 

## Motivation
[Explain the reason for these changes and what problem they solve or improvement they bring.]

## Testing Procedures
[Include step-by-step instructions for testing the changes. This may involve setting up a testing environment, running tests, and specifying expected outcomes etc.]

## Checklist
- [ ] Code adheres to project coding standards.
- [ ] Tests cover the added or modified code.
- [ ] Documentation has been updated, if necessary.
- [ ] All new and existing tests pass successfully.
- [ ] The pull request is up to date with the latest changes from the main branch.

## Reviewer Guidelines
[Provide guidance for reviewers. Describe specific aspects they should focus on during the review and any special testing or use cases they should consider.]

## Screenshots or Visuals
[Include any relevant screenshots, diagrams, or visual aids to help reviewers understand the changes visually.]

## Additional Information
[Add any other pertinent details, such as links to related issues or documentation.]

Fixes #130

### CODE REVIEW

**Comment by JenBauer** [comment]
This is a neat idea, and it works functionally, but I'm not sure that we need it on these pages.  We also don't have an Issue open asking for this particular feature at this time.  I'll defer to @klmansel on this one.

**Comment by git-create-devben** [comment]
@JenBauer I wanted to open an issue for that but I feel it's not necessary since it's a small features and I guess it'll be more easier for folks to go back up to the beginning of the page , but it's okay if you feel it's not necessary. If you want me to close it now I'll or if you want me to open an issue for it, no problem also. Thanks

**Comment by git-create-devben** [comment]
> > @JenBauer I wanted to open an issue for that but I feel it's not necessary since it's a small features and I guess it'll be more easier for folks to go back up to the beginning of the page , but it's okay if you feel it's not necessary. If you want me to close it now I'll or if you want me to open an issue for it, no problem also. Thanks
> 
> Thanks for contributing again @git-create-devben! We'd prefer an issue be opened no matter how small the feature so design decisions can be made. In this instance, I do like the idea of having the back-to-top button, but would prefer it to be floating like [this implementation](https://codepen.io/avabarok/pen/WNajjrz) and match our colors.

So should I create an issue for that ? and you mean I should remove the Icon ?

**Comment by JenBauer** [comment]
Hi @git-create-devben, please create an issue and link it to this PR.  Yes, let's remove the icon and otherwise match the colors to the chapter colors used in the Readme file.  Thank you!

**Review by JenBauer — CHANGES_REQUESTED** [review]
Hi @git-create-devben, please create an issue and link it to this PR. Yes, let's remove the icon and otherwise match the colors to the chapter colors used in the Readme file. Thank you!

**Comment by klmansel** [comment]
@git-create-devben is this ready for review now?

**Comment by git-create-devben** [comment]
@klmansel  am busy that time so to let you guys know am working on it i put it on draft, So I'll work on it now

**Comment by git-create-devben** [comment]
I use the same method they use for the headline and I also remove the icon so check it @JenBauer and @klmansel and tell me what you think. Thanks

**Comment by JenBauer** [comment]
Hi @git-create-devben, I'm not sure what's up on my end, but I am having difficulty previewing this properly.  When I check this out locally, I'm still seeing the old icon on the Getting Started page, but it looks like there is a new SVG for the Readme.  Is that what is intended?  For me in VS Code preview, though, the new SVG looks like a broken image, so I'm not sure if this is just me or something else.  @klmansel, is there anything I'm missing here in reviewing this?

**Comment by git-create-devben** [comment]
@JenBauer here you go check it out

**Comment by JenBauer** [comment]
Hi @git-create-devben, I'm seeing the formatting updated now, but I'm not seeing the float behavior that @klmansel requested.  Is this update only for changing the style?

**Comment by JenBauer** [comment]
Hi @klmansel, can we clear this issue without the float for the time being, or is it straightforward to implement?  Any guidance you can provide here would be great, thanks!

**Review by klmansel — APPROVED** [review]
Approved - fixed formatting and we can fix the other part in the future - thanks @git-create-devben!

**Pull request merged**
