### PR TITLE
docs: adding online event videos to documents

### PR DESCRIPTION
**Pull request by kodebae**
# Pull Request

## Description
This pull request is adding YouTube videos for the WWCode Greenville chapter to the documentation. 

## Motivation
To spread awareness for our online events and to promote the wonder women in our chapter. 

## Testing Procedures
Manual testing implemented. Links have been manually tested one by one. 

## Checklist
- [x ] Code adheres to project coding standards.
- [ x] Tests cover the added or modified code.
- [x ] Documentation has been updated, if necessary.
- [x ] All new and existing tests pass successfully.
- [ x] The pull request is up to date with the latest changes from the main branch.

## Reviewer Guidelines
[Provide guidance for reviewers. Describe specific aspects they should focus on during the review and any special testing or use cases they should consider.] 

## Screenshots or Visuals
[Include any relevant screenshots, diagrams, or visual aids to help reviewers understand the changes visually.]

## Additional Information
[Add any other pertinent details, such as links to related issues or documentation.]

Fixes #[Issue Number]

### CODE REVIEW

**Review by JenBauer — APPROVED** [review]
Good stuff, thank you!

**Comment by kodebae** [comment]
I wasn't sure if this page was supposed to be added to the main README.md. If we would like to implement a link for that, let me know and I can get it added to the table of contents if need be.

**Comment by JenBauer** [comment]
@kodebae, that's a great idea!

**Comment by JenBauer** [comment]
We just chatted - we'll do the link in another PR, merging this for the time being.

**Comment by kodebae** [comment]
Thank you so much Jen.

**Pull request merged**
