### PR TITLE
Update with Chapter 2 CollaborativeFiction-DebugMansion.md

### PR DESCRIPTION
**Pull request by Ali-Herrera**

### CODE REVIEW

**Review by klmansel — CHANGES_REQUESTED** [review]
Awesome, Ali! Can I ask that you leave a note on what tech you used to generate your chapter after the Chapter 2 heading?

**Comment by pksuperduper** [comment]
Cool!  I read Jen's Chapter 1 and your Chapter 2.  I have an idea for a Chapter however I wanted to first see -- how did you write yours Ali?  Was it all by your mind and hand-written, or your mind + ChapGPT or, another creative way?

**Comment by Ali-Herrera** [comment]
Added! I used ChatGPT. I put in a couple ideas of what i wanted it to be about along with chapter 1 and then it wrote it all eloquently for me. :)

**Review by JenBauer — APPROVED** [review]
Thank you for the update, approved!

**Pull request merged**
